import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Search } from "tabler-icons-react";
import { Box, Button, TextInput } from "@mantine/core";
import { Masonry } from "@mui/lab";

const Home: NextPage = () => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>My Unsplash</title>
        <meta
          name="Unsplash image uploads"
          content="Generated by create next app"
        />
      </Head>
      <nav className={styles.nav__container}>
        <Box className={styles.nav__left}>
          <Image
            width="138px"
            height="26px"
            src="/my_unsplash_logo.svg"
            alt="logo"
          />
          <TextInput
            className={styles.search__input}
            placeholder="Search by name"
            icon={<Search />}
          />
        </Box>
        <Box>
          <Button className={styles.add_photo_btn}>Add a photo</Button>
        </Box>
      </nav>
      <Box>
        <Masonry columns={3} spacing={3}>
          <Box>1</Box>
          <Box>2</Box>
          <Box>3</Box>
          <Box>4</Box>
        </Masonry>
      </Box>
    </Box>
  );
};

export default Home;
